# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AAChartKitTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AAChartKitTest
  pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

  target 'AAChartKitTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AAChartKitTestUITests' do
    # Pods for testing
  end

end
